package com.toolhelper.domain.kylin;

/** 阶段5允许的固定操作集合，API不得接受任意 shell。 */
public enum KylinOperation {
    ACTIVATION_SCAN,
    REBOOT_SCAN, REBOOT_DEPLOY, REBOOT_UNINSTALL, REBOOT_VERIFY,
    LOG_CLEAN_SCAN, LOG_CLEAN_DEPLOY, LOG_CLEAN_UNINSTALL, LOG_CLEAN_VERIFY,
    VNC_SCAN, VNC_DEPLOY, VNC_START, VNC_STOP, VNC_UNINSTALL,
    OPENGAUSS_SCAN, OPENGAUSS_DEPLOY, OPENGAUSS_RESTORE, OPENGAUSS_RELOAD,
    VULNERABILITY_SCAN, VULNERABILITY_REPAIR, VULNERABILITY_VERIFY,
    OPTIMIZATION_SCAN, OPTIMIZATION_APPLY, OPTIMIZATION_RESTORE, OPTIMIZATION_VERIFY
}
