<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ToolHelper.Agent.Application\ToolHelper.Agent.Application.csproj" />
    <ProjectReference Include="..\ToolHelper.Agent.Domain\ToolHelper.Agent.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
